version: "3.7"

services:
    vue-e-commerce:
        container_name: vue-e-commerce
        build:
            context: ./vue-e-commerce
        volumes:
            - .:/app
        ports:
            - 8080:8080
        command: bash -c 'cd vue-e-commerce && npm install && npm run serve'
        networks:
            - webnet
        restart: unless-stopped
        depends_on:
            - laravel-e-commerce
    laravel-e-commerce:
        container_name: laravel-e-commerce
        build:
            context: ./laravel-e-commerce
        volumes:
            - .:/app
        ports:
            - 8000:8000
        command: bash -c 'cd laravel-e-commerce && composer install && php artisan migrate && php artisan db:seed && php artisan serve --host 0.0.0.0 --port 8000'
        networks:
            - webnet
        restart: unless-stopped
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: mysql:5.7
        networks:
            - webnet
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: products
        ports:
            - 12574:3306
        restart: unless-stopped
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysqls
networks:
    webnet:

volumes:
    mysql:
    mysql_config:
